<?php

declare(strict_types=1);

namespace Core\Routing;

use Core\Config\Config;
use Throwable;

/**
 * @file RouteCache.php
 * @brief Compiled route table persisted as a PHP file (served from OPcache shared memory).
 */

/**
 * @class RouteCache
 * @brief Stores and restores the router's attribute routes so that requests skip directory scans,
 *        controller autoloading and attribute reflection.
 *
 * Configuration (config/routing.php):
 *  - `routing.cache` (bool): enable the cache.
 *  - `routing.cache_path` (string): cache file location.
 *  - `routing.cache_validate` (bool|null): compare controller file modification times on every request
 *    (null = follow `app.debug`). Without validation, rebuild with `php bin/frasm route:cache` after deploys.
 *
 * The file is written atomically (temp file + rename) and invalidated in OPcache.
 */
class RouteCache
{
    /**
     * @var int Cache format version; bump when the Route array layout changes.
     */
    public const VERSION = 2;

    /**
     * @brief Checks whether route caching is enabled.
     *
     * @return bool
     */
    public function isEnabled(): bool
    {
        return (bool)Config::get('routing.cache', false);
    }

    /**
     * @brief Checks whether the cache must be validated against source modification times.
     *
     * @return bool
     */
    public function shouldValidate(): bool
    {
        $validate = Config::get('routing.cache_validate');
        return $validate === null ? (bool)Config::get('app.debug', false) : (bool)$validate;
    }

    /**
     * @brief Returns the cache file path.
     *
     * @return string
     */
    public function path(): string
    {
        return (string)Config::get(
            'routing.cache_path',
            FRASM_STORAGE_DIR . DIRECTORY_SEPARATOR . 'cache' . DIRECTORY_SEPARATOR . 'routes.php'
        );
    }

    /**
     * @brief Loads the cached payload.
     *
     * @return array{version: int, sources: array<string, int>, routes: list<array<string, mixed>>}|null Null when missing, corrupt or outdated.
     */
    public function load(): ?array
    {
        $path = $this->path();
        if (!is_file($path)) {
            return null;
        }

        try {
            $data = include $path;
        } catch (Throwable) {
            return null;
        }

        if (!is_array($data) || ($data['version'] ?? null) !== self::VERSION || !is_array($data['routes'] ?? null)) {
            return null;
        }

        return $data;
    }

    /**
     * @brief Checks that the recorded source files still exist with unchanged modification times
     *        and that no controller file was added or removed.
     *
     * @param array{sources: array<string, int>} $data Cached payload.
     * @param list<string> $currentFiles Source files discovered now.
     * @return bool
     */
    public function isFresh(array $data, array $currentFiles): bool
    {
        $sources = $data['sources'] ?? [];

        foreach ($currentFiles as $file) {
            if (!isset($sources[$file])) {
                return false;
            }
        }

        foreach ($sources as $file => $mtime) {
            if (@filemtime($file) !== $mtime) {
                return false;
            }
        }

        return true;
    }

    /**
     * @brief Writes the cache atomically.
     *
     * @param list<array<string, mixed>> $routes Exported routes.
     * @param list<string> $sourceFiles Files the routes were built from.
     * @return bool False when the cache directory is not writable.
     */
    public function write(array $routes, array $sourceFiles): bool
    {
        $sources = [];
        foreach ($sourceFiles as $file) {
            $mtime = @filemtime($file);
            if ($mtime !== false) {
                $sources[$file] = $mtime;
            }
        }

        $payload = ['version' => self::VERSION, 'sources' => $sources, 'routes' => $routes];
        $content = "<?php\n\n// Generated by Core\\Routing\\RouteCache on " . date('c') . ". Do not edit.\n\nreturn "
            . var_export($payload, true) . ";\n";

        $path = $this->path();
        $directory = dirname($path);

        if (!is_dir($directory)) {
            if (!@mkdir($directory, 0775, true) && !is_dir($directory)) {
                return false;
            }
            @chmod($directory, 0775);
        }

        $temp = $directory . DIRECTORY_SEPARATOR . '.routes.' . bin2hex(random_bytes(6)) . '.tmp';
        if (@file_put_contents($temp, $content, LOCK_EX) === false) {
            return false;
        }

        @chmod($temp, 0664);
        if (!@rename($temp, $path)) {
            @unlink($temp);
            return false;
        }

        $this->invalidateOpcache($path);

        return true;
    }

    /**
     * @brief Deletes the cache file.
     *
     * @return bool True when no cache file remains.
     */
    public function clear(): bool
    {
        $path = $this->path();
        if (!is_file($path)) {
            return true;
        }

        $this->invalidateOpcache($path);
        return @unlink($path);
    }

    /**
     * @brief Drops the file from OPcache so the new content is used immediately.
     *
     * @param string $path Cache file path.
     * @return void
     */
    protected function invalidateOpcache(string $path): void
    {
        if (function_exists('opcache_invalidate')) {
            @opcache_invalidate($path, true);
        }
    }
}
