<?php

declare(strict_types=1);

namespace Core\Security;

use Core\Config\Config;
use Core\Exceptions\CoreException;

/**
 * @file Signer.php
 * @brief HMAC signing and verification derived from the application key.
 */

/**
 * @class Signer
 * @brief Produces purpose-bound HMAC-SHA256 signatures and signed, expiring tokens.
 *
 * A separate key is derived for every purpose (HKDF), so a signature created for one feature
 * (e.g. live component state) can never be replayed against another (e.g. push actions).
 * Requires `app.key` ("base64:<32+ random bytes>", generated by `php bin/key.php`).
 */
final class Signer
{
    /**
     * @var array<string, string> Derived keys cached per purpose.
     */
    private static array $keys = [];

    /**
     * @brief Prevents instantiation of the static helper.
     */
    private function __construct()
    {
    }

    /**
     * @brief Generates a new application key in the "base64:..." format.
     *
     * @return string
     */
    public static function generateKey(): string
    {
        return 'base64:' . base64_encode(random_bytes(32));
    }

    /**
     * @brief Signs data for a purpose.
     *
     * @param string $purpose Domain separation label (e.g. 'live-component').
     * @param string $data Data to sign.
     * @return string 64-character hex signature.
     * @throws CoreException If app.key is missing or too short.
     */
    public static function sign(string $purpose, string $data): string
    {
        return hash_hmac('sha256', $data, self::key($purpose));
    }

    /**
     * @brief Verifies a signature in constant time.
     *
     * @param string $purpose Domain separation label.
     * @param string $data Signed data.
     * @param string $signature Signature to check.
     * @return bool
     * @throws CoreException If app.key is missing or too short.
     */
    public static function verify(string $purpose, string $data, string $signature): bool
    {
        return hash_equals(self::sign($purpose, $data), $signature);
    }

    /**
     * @brief Creates a URL-safe token carrying a JSON payload and an expiry.
     *
     * @param string $purpose Domain separation label.
     * @param array<string, mixed> $payload Public (not encrypted) claims.
     * @param int $ttl Validity in seconds.
     * @return string Token "<base64url json>.<signature>".
     * @throws CoreException If app.key is missing or too short.
     */
    public static function token(string $purpose, array $payload, int $ttl): string
    {
        $payload['exp'] = time() + max(1, $ttl);
        $body = rtrim(strtr(base64_encode(json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR)), '+/', '-_'), '=');

        return $body . '.' . self::sign($purpose, $body);
    }

    /**
     * @brief Verifies a token and returns its payload.
     *
     * @param string $purpose Domain separation label.
     * @param string $token Token created by token().
     * @return array<string, mixed>|null Payload, or null when malformed, forged or expired.
     * @throws CoreException If app.key is missing or too short.
     */
    public static function parseToken(string $purpose, string $token): ?array
    {
        $parts = explode('.', $token);
        if (count($parts) !== 2 || !self::verify($purpose, $parts[0], $parts[1])) {
            return null;
        }

        $json = base64_decode(strtr($parts[0], '-_', '+/'), true);
        $payload = $json === false ? null : json_decode($json, true);

        if (!is_array($payload) || !is_int($payload['exp'] ?? null) || $payload['exp'] < time()) {
            return null;
        }

        return $payload;
    }

    /**
     * @brief Derives (and caches) the key for a purpose from app.key.
     *
     * @param string $purpose Domain separation label.
     * @return string Binary key.
     * @throws CoreException If app.key is missing or shorter than 32 bytes.
     */
    private static function key(string $purpose): string
    {
        if (isset(self::$keys[$purpose])) {
            return self::$keys[$purpose];
        }

        $configured = (string)Config::get('app.key', '');
        $raw = str_starts_with($configured, 'base64:') ? base64_decode(substr($configured, 7), true) : $configured;

        if (!is_string($raw) || strlen($raw) < 32) {
            throw new CoreException("Missing or too short app.key (min. 32 bytes). Generate one with `php bin/key.php` and put it into config/local.php.");
        }

        return self::$keys[$purpose] = hash_hkdf('sha256', $raw, 32, 'frasm:' . $purpose);
    }
}
